"use strict";
/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __async = (__this, __arguments, generator) => {
  return new Promise((resolve, reject) => {
    var fulfilled = (value) => {
      try {
        step(generator.next(value));
      } catch (e) {
        reject(e);
      }
    };
    var rejected = (value) => {
      try {
        step(generator.throw(value));
      } catch (e) {
        reject(e);
      }
    };
    var step = (x) => x.done ? resolve(x.value) : Promise.resolve(x.value).then(fulfilled, rejected);
    step((generator = generator.apply(__this, __arguments)).next());
  });
};

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ObsidianAutoCardLink
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  showInMenuItem: true,
  enhanceDefaultPaste: false
};
var ObsidianAutoCardLinkSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Enhance Default Paste").setDesc(
      "Fetch the link metadata when pasting a url in the editor with the default paste command"
    ).addToggle((val) => {
      if (!this.plugin.settings)
        return;
      return val.setValue(this.plugin.settings.enhanceDefaultPaste).onChange((value) => __async(this, null, function* () {
        if (!this.plugin.settings)
          return;
        this.plugin.settings.enhanceDefaultPaste = value;
        yield this.plugin.saveSettings();
      }));
    });
    new import_obsidian.Setting(containerEl).setName("Add commands in menu item").setDesc("Whether to add commands in right click menu items").addToggle((val) => {
      if (!this.plugin.settings)
        return;
      return val.setValue(this.plugin.settings.showInMenuItem).onChange((value) => __async(this, null, function* () {
        if (!this.plugin.settings)
          return;
        this.plugin.settings.showInMenuItem = value;
        yield this.plugin.saveSettings();
      }));
    });
  }
};

// src/regex.ts
var urlRegex = /^(https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]+\.[^\s]{2,}|www\.[a-zA-Z0-9]+\.[^\s]{2,})$/i;
var lineRegex = /(https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]+\.[^\s]{2,}|www\.[a-zA-Z0-9]+\.[^\s]{2,})/gi;
var linkRegex = /^\[([^[\]]*)\]\((https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]+\.[^\s]{2,}|www\.[a-zA-Z0-9]+\.[^\s]{2,})\)$/i;
var linkLineRegex = /\[([^[\]]*)\]\((https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]+\.[^\s]{2,}|www\.[a-zA-Z0-9]+\.[^\s]{2,})\)/gi;
var imageRegex = /\.(gif|jpe?g|tiff?|png|webp|bmp|tga|psd|ai)$/i;

// src/editor_enhancements.ts
var EditorExtensions = class {
  static getSelectedText(editor) {
    if (!editor.somethingSelected()) {
      const wordBoundaries = this.getWordBoundaries(editor);
      editor.setSelection(wordBoundaries.start, wordBoundaries.end);
    }
    return editor.getSelection();
  }
  static isCursorWithinBoundaries(cursor, match) {
    var _a;
    const startIndex = (_a = match.index) != null ? _a : 0;
    const endIndex = startIndex + match[0].length;
    return startIndex <= cursor.ch && cursor.ch <= endIndex;
  }
  static getWordBoundaries(editor) {
    var _a, _b;
    const cursor = editor.getCursor();
    const lineText = editor.getLine(cursor.line);
    const linksInLine = lineText.matchAll(linkLineRegex);
    for (const match of linksInLine) {
      if (this.isCursorWithinBoundaries(cursor, match)) {
        const startCh = (_a = match.index) != null ? _a : 0;
        return {
          start: {
            line: cursor.line,
            ch: startCh
          },
          end: { line: cursor.line, ch: startCh + match[0].length }
        };
      }
    }
    const urlsInLine = lineText.matchAll(lineRegex);
    for (const match of urlsInLine) {
      if (this.isCursorWithinBoundaries(cursor, match)) {
        const startCh = (_b = match.index) != null ? _b : 0;
        return {
          start: { line: cursor.line, ch: startCh },
          end: { line: cursor.line, ch: startCh + match[0].length }
        };
      }
    }
    return {
      start: cursor,
      end: cursor
    };
  }
  static getEditorPositionFromIndex(content, index) {
    const substr = content.substr(0, index);
    let l = 0;
    let offset = -1;
    let r = -1;
    for (; (r = substr.indexOf("\n", r + 1)) !== -1; l++, offset = r)
      ;
    offset += 1;
    const ch = content.substr(offset, index - offset).length;
    return { line: l, ch };
  }
};

// src/checkif.ts
var CheckIf = class {
  static isUrl(text) {
    const regex = new RegExp(urlRegex);
    return regex.test(text);
  }
  static isImage(text) {
    const regex = new RegExp(imageRegex);
    return regex.test(text);
  }
  static isLinkedUrl(text) {
    const regex = new RegExp(linkRegex);
    return regex.test(text);
  }
};

// src/code_block_generator.ts
var import_obsidian2 = require("obsidian");

// src/link_metadata_parser.ts
var LinkMetadataParser = class {
  constructor(url, htmlText) {
    this.url = url;
    const parser = new DOMParser();
    const htmlDoc = parser.parseFromString(htmlText, "text/html");
    this.htmlDoc = htmlDoc;
  }
  parse() {
    return __async(this, null, function* () {
      const title = LinkMetadataParser.sanitizeText(this.getTitle());
      if (!title)
        return;
      const description = LinkMetadataParser.sanitizeText(this.getDescription());
      const { hostname } = new URL(this.url);
      const favicon = yield this.getFavicon();
      const image = yield this.getImage();
      return {
        url: this.url,
        title,
        description,
        host: hostname,
        favicon,
        image,
        indent: 0
      };
    });
  }
  getTitle() {
    var _a, _b;
    const ogTitle = (_a = this.htmlDoc.querySelector("meta[property='og:title']")) == null ? void 0 : _a.getAttribute("content");
    if (ogTitle)
      return ogTitle;
    const title = (_b = this.htmlDoc.querySelector("title")) == null ? void 0 : _b.textContent;
    if (title)
      return title;
  }
  getDescription() {
    var _a, _b;
    const ogDescription = (_a = this.htmlDoc.querySelector("meta[property='og:description']")) == null ? void 0 : _a.getAttribute("content");
    if (ogDescription)
      return ogDescription;
    const metaDescription = (_b = this.htmlDoc.querySelector("meta[name='description']")) == null ? void 0 : _b.getAttribute("content");
    if (metaDescription)
      return metaDescription;
  }
  getFavicon() {
    return __async(this, null, function* () {
      var _a;
      const favicon = (_a = this.htmlDoc.querySelector("link[rel='icon']")) == null ? void 0 : _a.getAttribute("href");
      if (favicon)
        return yield this.fixImageUrl(favicon);
    });
  }
  getImage() {
    return __async(this, null, function* () {
      var _a;
      const ogImage = (_a = this.htmlDoc.querySelector("meta[property='og:image']")) == null ? void 0 : _a.getAttribute("content");
      if (ogImage)
        return yield this.fixImageUrl(ogImage);
    });
  }
  fixImageUrl(url) {
    return __async(this, null, function* () {
      if (url === void 0)
        return "";
      const { hostname } = new URL(this.url);
      let image = url;
      if (url && url.startsWith("//")) {
        const testUrlHttps = `https:${url}`;
        const testUrlHttp = `http:${url}`;
        if (yield checkUrlAccessibility(testUrlHttps)) {
          image = testUrlHttps;
        } else if (yield checkUrlAccessibility(testUrlHttp)) {
          image = testUrlHttp;
        }
      } else if (url && url.startsWith("/") && hostname) {
        const testUrlHttps = `https://${hostname}${url}`;
        const testUrlHttp = `http://${hostname}${url}`;
        const resUrlHttps = yield checkUrlAccessibility(testUrlHttps);
        const resUrlHttp = yield checkUrlAccessibility(testUrlHttp);
        if (resUrlHttps) {
          image = testUrlHttps;
        } else if (resUrlHttp) {
          image = testUrlHttp;
        }
      }
      function checkUrlAccessibility(url2) {
        return __async(this, null, function* () {
          return new Promise((resolve) => {
            const img = new Image();
            img.onload = () => resolve(true);
            img.onerror = () => resolve(false);
            img.src = url2;
          });
        });
      }
      return image;
    });
  }
  static sanitizeText(text) {
    if (!text)
      return void 0;
    return text.replace(/\r\n|\n|\r/g, " ").replace(/\\/g, "\\\\").replace(/"/g, '\\"').trim();
  }
};

// src/code_block_generator.ts
var CodeBlockGenerator = class {
  constructor(editor) {
    this.editor = editor;
  }
  convertUrlToCodeBlock(url) {
    return __async(this, null, function* () {
      const selectedText = this.editor.getSelection();
      const pasteId = this.createBlockHash();
      const fetchingText = `[Fetching Data#${pasteId}](${url})`;
      this.editor.replaceSelection(fetchingText);
      try {
        const linkMetadata = yield this.fetchLinkMetadata(url);
        const text = this.editor.getValue();
        const start = text.indexOf(fetchingText);
        if (start < 0) {
          console.log(`Unable to find text "${fetchingText}" in current editor, bailing out; link ${url}`);
          return;
        }
        const end = start + fetchingText.length;
        const startPos = EditorExtensions.getEditorPositionFromIndex(text, start);
        const endPos = EditorExtensions.getEditorPositionFromIndex(text, end);
        if (!linkMetadata) {
          new import_obsidian2.Notice("Couldn't fetch link metadata");
          this.editor.replaceRange(selectedText || `[${url}](${url})`, startPos, endPos);
          return;
        }
        this.editor.replaceRange(this.genCodeBlock(linkMetadata), startPos, endPos);
      } catch (e) {
        console.error("convertUrlToCodeBlock failed:", e);
        new import_obsidian2.Notice("Couldn't fetch link metadata");
        const text = this.editor.getValue();
        const start = text.indexOf(fetchingText);
        if (start >= 0) {
          const end = start + fetchingText.length;
          const startPos = EditorExtensions.getEditorPositionFromIndex(text, start);
          const endPos = EditorExtensions.getEditorPositionFromIndex(text, end);
          this.editor.replaceRange(selectedText || `[${url}](${url})`, startPos, endPos);
        }
      }
    });
  }
  genCodeBlock(linkMetadata) {
    const codeBlockTexts = ["\n```cardlink"];
    codeBlockTexts.push(`url: ${linkMetadata.url}`);
    codeBlockTexts.push(`title: "${linkMetadata.title}"`);
    if (linkMetadata.description)
      codeBlockTexts.push(`description: "${linkMetadata.description}"`);
    if (linkMetadata.host)
      codeBlockTexts.push(`host: ${linkMetadata.host}`);
    if (linkMetadata.favicon)
      codeBlockTexts.push(`favicon: ${linkMetadata.favicon}`);
    if (linkMetadata.image)
      codeBlockTexts.push(`image: ${linkMetadata.image}`);
    codeBlockTexts.push("```\n");
    return codeBlockTexts.join("\n");
  }
  createBlockHash() {
    let result = "";
    const characters = "abcdefghijklmnopqrstuvwxyz0123456789";
    const charactersLength = characters.length;
    for (let i = 0; i < 4; i++) {
      result += characters.charAt(Math.floor(Math.random() * charactersLength));
    }
    return result;
  }
  fetchLinkMetadata(url) {
    return __async(this, null, function* () {
      if (this.isYouTubeUrl(url))
        return this.fetchYouTubeLinkMetadata(url);
      if (this.isRedditUrl(url))
        return this.fetchRedditLinkMetadata(url);
      const res = yield (() => __async(this, null, function* () {
        try {
          return (0, import_obsidian2.requestUrl)({
            url,
            headers: {
              "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
              "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
              "Accept-Language": "en-US,en;q=0.5"
            }
          });
        } catch (e) {
          console.log(e);
          return;
        }
      }))();
      if (!res || res.status != 200) {
        console.log(`bad response. response status code was ${res == null ? void 0 : res.status}`);
        return {
          url,
          title: "Fetch error",
          description: res ? `HTTP ${res.status}` : "Request failed",
          host: new URL(url).hostname,
          indent: 0
        };
      }
      const parser = new LinkMetadataParser(url, res.text);
      return parser.parse();
    });
  }
  isYouTubeUrl(url) {
    return /^https?:\/\/(www\.)?(youtube\.com\/watch|youtu\.be\/)/.test(url);
  }
  fetchYouTubeLinkMetadata(url) {
    return __async(this, null, function* () {
      var _a, _b;
      const oembedUrl = `https://www.youtube.com/oembed?url=${encodeURIComponent(url)}&format=json`;
      const res = yield (() => __async(this, null, function* () {
        try {
          return (0, import_obsidian2.requestUrl)({ url: oembedUrl });
        } catch (e) {
          console.log(e);
          return;
        }
      }))();
      if (!res || res.status !== 200)
        return;
      const data = JSON.parse(res.text);
      const videoId = this.getYouTubeVideoId(url);
      const image = videoId ? yield this.getBestYouTubeThumbnail(videoId) : data.thumbnail_url;
      return {
        url,
        title: (_a = LinkMetadataParser.sanitizeText(data.title)) != null ? _a : data.title,
        description: (_b = LinkMetadataParser.sanitizeText(`By ${data.author_name}`)) != null ? _b : `By ${data.author_name}`,
        host: "www.youtube.com",
        favicon: "https://www.youtube.com/favicon.ico",
        image,
        indent: 0
      };
    });
  }
  getYouTubeVideoId(url) {
    const match = url.match(
      /(?:youtube\.com\/watch\?.*v=|youtu\.be\/)([a-zA-Z0-9_-]{11})/
    );
    return match == null ? void 0 : match[1];
  }
  getBestYouTubeThumbnail(videoId) {
    return __async(this, null, function* () {
      const qualities = ["maxresdefault", "sddefault", "hqdefault"];
      for (const q of qualities) {
        const thumbUrl = `https://i.ytimg.com/vi/${videoId}/${q}.jpg`;
        const res = yield (() => __async(this, null, function* () {
          try {
            return (0, import_obsidian2.requestUrl)({ url: thumbUrl });
          } catch (e) {
            return;
          }
        }))();
        if (res && res.status === 200)
          return thumbUrl;
      }
      return `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`;
    });
  }
  isRedditUrl(url) {
    return /reddit\.com\/(r|u|user)\//.test(url);
  }
  fetchRedditLinkMetadata(url) {
    return __async(this, null, function* () {
      const normalized = url.replace("old.reddit.com", "www.reddit.com").replace(/\/?$/, "/");
      const isPost = /reddit\.com\/r\/\w+\/comments\//.test(normalized);
      const isSubreddit = /reddit\.com\/r\/\w+\/?$/.test(normalized);
      const isUser = /reddit\.com\/(?:u|user)\/\w+/.test(normalized);
      if (isPost) {
        return this.fetchRedditPost(url, normalized);
      } else if (isSubreddit) {
        return this.fetchRedditSubreddit(url, normalized);
      } else if (isUser) {
        return this.fetchRedditUser(url, normalized);
      }
    });
  }
  fetchRedditPost(originalUrl, normalized) {
    return __async(this, null, function* () {
      var _a, _b, _c, _d, _e, _f, _g, _h, _i, _j;
      const jsonUrl = normalized.replace(/\/?$/, ".json") + "?limit=1";
      const res = yield (() => __async(this, null, function* () {
        try {
          return (0, import_obsidian2.requestUrl)({
            url: jsonUrl,
            headers: { "User-Agent": "obsidian-auto-card-link/1.0" }
          });
        } catch (e) {
          console.log(e);
          return;
        }
      }))();
      if (!res || res.status !== 200)
        return;
      const data = JSON.parse(res.text);
      const post = (_d = (_c = (_b = (_a = data[0]) == null ? void 0 : _a.data) == null ? void 0 : _b.children) == null ? void 0 : _c[0]) == null ? void 0 : _d.data;
      if (!post)
        return;
      const rawImage = (_i = (_h = (_g = (_f = (_e = post.preview) == null ? void 0 : _e.images) == null ? void 0 : _f[0]) == null ? void 0 : _g.source) == null ? void 0 : _h.url) == null ? void 0 : _i.replace(/&amp;/g, "&");
      const image = rawImage && !["self", "default", "nsfw", ""].includes(rawImage) ? rawImage : void 0;
      return {
        url: originalUrl,
        title: (_j = LinkMetadataParser.sanitizeText(post.title)) != null ? _j : post.title,
        description: LinkMetadataParser.sanitizeText(
          post.selftext ? post.selftext.slice(0, 200).replace(/\n/g, " ") + "\u2026" : `Posted by u/${post.author} in r/${post.subreddit}`
        ),
        host: "www.reddit.com",
        favicon: "https://www.reddit.com/favicon.ico",
        image,
        indent: 0
      };
    });
  }
  fetchRedditSubreddit(originalUrl, normalized) {
    return __async(this, null, function* () {
      var _a, _b;
      const aboutUrl = normalized.replace(/\/?$/, "/about.json");
      const res = yield (() => __async(this, null, function* () {
        try {
          return (0, import_obsidian2.requestUrl)({
            url: aboutUrl,
            headers: { "User-Agent": "obsidian-auto-card-link/1.0" }
          });
        } catch (e) {
          console.log(e);
          return;
        }
      }))();
      if (!res || res.status !== 200)
        return;
      const sub = (_a = JSON.parse(res.text)) == null ? void 0 : _a.data;
      if (!sub)
        return;
      const rawIcon = sub.community_icon || sub.icon_img || "";
      const image = rawIcon.split("?")[0] || void 0;
      return {
        url: originalUrl,
        title: `r/${sub.display_name}`,
        description: ((_b = sub.public_description) == null ? void 0 : _b.trim()) || void 0,
        host: "www.reddit.com",
        favicon: "https://www.reddit.com/favicon.ico",
        image: image || void 0,
        indent: 0
      };
    });
  }
  fetchRedditUser(originalUrl, normalized) {
    return __async(this, null, function* () {
      var _a, _b, _c, _d;
      const match = normalized.match(/reddit\.com\/(?:u|user)\/(\w+)/);
      if (!match)
        return;
      const username = match[1];
      const aboutUrl = `https://www.reddit.com/user/${username}/about.json`;
      const res = yield (() => __async(this, null, function* () {
        try {
          return (0, import_obsidian2.requestUrl)({
            url: aboutUrl,
            headers: { "User-Agent": "obsidian-auto-card-link/1.0" }
          });
        } catch (e) {
          console.log(e);
          return;
        }
      }))();
      if (!res || res.status !== 200)
        return;
      const user = (_a = JSON.parse(res.text)) == null ? void 0 : _a.data;
      if (!user)
        return;
      return {
        url: originalUrl,
        title: `u/${user.name}`,
        description: ((_c = (_b = user.subreddit) == null ? void 0 : _b.public_description) == null ? void 0 : _c.trim()) || void 0,
        host: "www.reddit.com",
        favicon: "https://www.reddit.com/favicon.ico",
        image: ((_d = user.icon_img) == null ? void 0 : _d.split("?")[0]) || void 0,
        indent: 0
      };
    });
  }
};

// src/code_block_processor.ts
var import_obsidian3 = require("obsidian");

// src/errors.ts
var YamlParseError = class extends Error {
};
var NoRequiredParamsError = class extends Error {
};

// src/code_block_processor.ts
var CodeBlockProcessor = class {
  constructor(app) {
    this.app = app;
  }
  run(source, el) {
    return __async(this, null, function* () {
      try {
        const data = this.parseLinkMetadataFromYaml(source);
        el.appendChild(this.genLinkEl(data));
      } catch (error) {
        if (error instanceof NoRequiredParamsError) {
          el.appendChild(this.genErrorEl(error.message));
        } else if (error instanceof YamlParseError) {
          el.appendChild(this.genErrorEl(error.message));
        } else if (error instanceof TypeError) {
          el.appendChild(
            this.genErrorEl("internal links must be surrounded by quotes.")
          );
          console.log(error);
        } else {
          console.log("Code Block: cardlink unknown error", error);
        }
      }
    });
  }
  parseLinkMetadataFromYaml(source) {
    let yaml;
    let indent = -1;
    source = source.split(/\r?\n|\r|\n/g).map(
      (line) => line.replace(/^\t+/g, (tabs) => {
        const n = tabs.length;
        if (indent < 0) {
          indent = n;
        }
        return " ".repeat(n);
      })
    ).join("\n");
    try {
      yaml = (0, import_obsidian3.parseYaml)(source);
    } catch (error) {
      console.log(error);
      throw new YamlParseError(
        "failed to parse yaml. Check debug console for more detail."
      );
    }
    if (!yaml || !yaml.url || !yaml.title) {
      throw new NoRequiredParamsError(
        "required params[url, title] are not found."
      );
    }
    return {
      url: yaml.url,
      title: yaml.title,
      description: yaml.description,
      host: yaml.host,
      favicon: yaml.favicon,
      image: yaml.image,
      indent
    };
  }
  genErrorEl(errorMsg) {
    const containerEl = document.createElement("div");
    containerEl.addClass("auto-card-link-error-container");
    const spanEl = document.createElement("span");
    spanEl.textContent = `cardlink error: ${errorMsg}`;
    containerEl.appendChild(spanEl);
    return containerEl;
  }
  genLinkEl(data) {
    const containerEl = document.createElement("div");
    containerEl.addClass("auto-card-link-container");
    containerEl.setAttr("data-auto-card-link-depth", data.indent);
    const cardEl = document.createElement("a");
    cardEl.addClass("auto-card-link-card");
    cardEl.setAttr("href", data.url);
    containerEl.appendChild(cardEl);
    const mainEl = document.createElement("div");
    mainEl.addClass("auto-card-link-main");
    cardEl.appendChild(mainEl);
    const titleEl = document.createElement("div");
    titleEl.addClass("auto-card-link-title");
    titleEl.textContent = data.title;
    mainEl.appendChild(titleEl);
    if (data.description) {
      const descriptionEl = document.createElement("div");
      descriptionEl.addClass("auto-card-link-description");
      descriptionEl.textContent = data.description;
      mainEl.appendChild(descriptionEl);
    }
    const hostEl = document.createElement("div");
    hostEl.addClass("auto-card-link-host");
    mainEl.appendChild(hostEl);
    if (data.favicon) {
      if (!CheckIf.isUrl(data.favicon))
        data.favicon = this.getLocalImagePath(data.favicon);
      const faviconEl = document.createElement("img");
      faviconEl.addClass("auto-card-link-favicon");
      faviconEl.setAttr("src", data.favicon);
      if (data.host) {
        const fallbackUrl = `https://www.google.com/s2/favicons?domain=${data.host}&sz=32`;
        faviconEl.onerror = () => {
          if (faviconEl.src !== fallbackUrl) {
            faviconEl.src = fallbackUrl;
          }
        };
      }
      hostEl.appendChild(faviconEl);
    }
    if (data.host) {
      const hostNameEl = document.createElement("span");
      hostNameEl.textContent = data.host;
      hostEl.appendChild(hostNameEl);
    }
    if (data.image) {
      if (!CheckIf.isUrl(data.image))
        data.image = this.getLocalImagePath(data.image);
      const thumbnailEl = document.createElement("img");
      thumbnailEl.addClass("auto-card-link-thumbnail");
      thumbnailEl.setAttr("src", data.image);
      thumbnailEl.setAttr("draggable", "false");
      cardEl.appendChild(thumbnailEl);
    }
    new import_obsidian3.ButtonComponent(containerEl).setClass("auto-card-link-copy-url").setClass("clickable-icon").setIcon("copy").setTooltip(`Copy URL
${data.url}`).onClick(() => {
      navigator.clipboard.writeText(data.url);
      new import_obsidian3.Notice("URL copied to your clipboard");
    });
    return containerEl;
  }
  getLocalImagePath(link) {
    var _a;
    link = link.slice(2, -2);
    const imageRelativePath = (_a = this.app.metadataCache.getFirstLinkpathDest(
      (0, import_obsidian3.getLinkpath)(link),
      ""
    )) == null ? void 0 : _a.path;
    if (!imageRelativePath)
      return link;
    return this.app.vault.adapter.getResourcePath(imageRelativePath);
  }
};

// src/main.ts
var ObsidianAutoCardLink = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.onPaste = (evt, editor) => __async(this, null, function* () {
      var _a;
      if (!((_a = this.settings) == null ? void 0 : _a.enhanceDefaultPaste))
        return;
      if (!navigator.onLine)
        return;
      if (evt.clipboardData == null)
        return;
      if (evt.clipboardData.files.length > 0)
        return;
      const clipboardText = evt.clipboardData.getData("text/plain");
      if (clipboardText == null || clipboardText == "")
        return;
      if (!CheckIf.isUrl(clipboardText) || CheckIf.isImage(clipboardText)) {
        return;
      }
      evt.stopPropagation();
      evt.preventDefault();
      const codeBlockGenerator = new CodeBlockGenerator(editor);
      yield codeBlockGenerator.convertUrlToCodeBlock(clipboardText);
      return;
    });
    this.onEditorMenu = (menu) => {
      var _a;
      if (!((_a = this.settings) == null ? void 0 : _a.showInMenuItem))
        return;
      menu.addItem((item) => {
        item.setTitle("Paste URL and enhance to card link").setIcon("paste").onClick(() => __async(this, null, function* () {
          const editor = this.getEditor();
          if (!editor)
            return;
          this.manualPasteAndEnhanceURL(editor);
        }));
      });
      if (!navigator.onLine)
        return;
      menu.addItem((item) => {
        item.setTitle("Enhance selected URL to card link").setIcon("link").onClick(() => {
          const editor = this.getEditor();
          if (!editor)
            return;
          this.enhanceSelectedURL(editor);
        });
      });
      return;
    };
  }
  onload() {
    return __async(this, null, function* () {
      yield this.loadSettings();
      this.registerMarkdownCodeBlockProcessor("cardlink", (source, el) => __async(this, null, function* () {
        const processor = new CodeBlockProcessor(this.app);
        yield processor.run(source, el);
      }));
      this.addCommand({
        id: "auto-card-link-paste-and-enhance",
        name: "Paste URL and enhance to card link",
        editorCallback: (editor) => __async(this, null, function* () {
          yield this.manualPasteAndEnhanceURL(editor);
        }),
        hotkeys: []
      });
      this.addCommand({
        id: "auto-card-link-enhance-selected-url",
        name: "Enhance selected URL to card link",
        editorCheckCallback: (checking, editor) => {
          if (!navigator.onLine)
            return false;
          if (checking)
            return true;
          this.enhanceSelectedURL(editor);
        },
        hotkeys: [
          {
            modifiers: ["Mod", "Shift"],
            key: "e"
          }
        ]
      });
      this.registerEvent(this.app.workspace.on("editor-paste", this.onPaste));
      this.registerEvent(this.app.workspace.on("editor-menu", this.onEditorMenu));
      this.addSettingTab(new ObsidianAutoCardLinkSettingTab(this.app, this));
    });
  }
  enhanceSelectedURL(editor) {
    return __async(this, null, function* () {
      const selectedText = (EditorExtensions.getSelectedText(editor) || "").trim();
      const codeBlockGenerator = new CodeBlockGenerator(editor);
      for (const line of selectedText.split(/[\n ]/)) {
        if (CheckIf.isUrl(line)) {
          yield codeBlockGenerator.convertUrlToCodeBlock(line);
        } else if (CheckIf.isLinkedUrl(line)) {
          const url = this.getUrlFromLink(line);
          yield codeBlockGenerator.convertUrlToCodeBlock(url);
        }
      }
    });
  }
  manualPasteAndEnhanceURL(editor) {
    return __async(this, null, function* () {
      const clipboardText = yield navigator.clipboard.readText();
      if (clipboardText == null || clipboardText == "") {
        return;
      }
      if (!navigator.onLine) {
        editor.replaceSelection(clipboardText);
        return;
      }
      if (!CheckIf.isUrl(clipboardText) || CheckIf.isImage(clipboardText)) {
        editor.replaceSelection(clipboardText);
        return;
      }
      const codeBlockGenerator = new CodeBlockGenerator(editor);
      yield codeBlockGenerator.convertUrlToCodeBlock(clipboardText);
      return;
    });
  }
  getEditor() {
    const view = this.app.workspace.getActiveViewOfType(import_obsidian4.MarkdownView);
    if (!view)
      return;
    return view.editor;
  }
  getUrlFromLink(link) {
    const urlRegex2 = new RegExp(linkRegex);
    const regExpExecArray = urlRegex2.exec(link);
    if (regExpExecArray === null || regExpExecArray.length < 2) {
      return "";
    }
    return regExpExecArray[2];
  }
  onunload() {
    console.log("unloading auto-card-link");
  }
  loadSettings() {
    return __async(this, null, function* () {
      this.settings = Object.assign({}, DEFAULT_SETTINGS, yield this.loadData());
    });
  }
  saveSettings() {
    return __async(this, null, function* () {
      yield this.saveData(this.settings);
    });
  }
};
